function changeBackgroundColor()
{
			if(document.getElementById('class').checked) {	document.getElementsByTagName("body")[0].style.backgroundColor="yellow";}
			else if(document.getElementById('class3').checked) {document.getElementsByTagName("body")[0].style.backgroundColor="green";}
			else if(document.getElementById('class2').checked) {document.getElementsByTagName("body")[0].style.backgroundColor="red";}

}
